PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS courses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL DEFAULT '',
  instructor TEXT NOT NULL DEFAULT '',
  coordinator TEXT NOT NULL DEFAULT '',
  department TEXT NOT NULL DEFAULT '',
  semester TEXT NOT NULL DEFAULT '',
  year INTEGER NOT NULL DEFAULT 0,
  credits INTEGER NOT NULL DEFAULT 0,
  target_pct REAL NOT NULL DEFAULT 75,
  student_pass_pct REAL NOT NULL DEFAULT 60,
  metric TEXT NOT NULL DEFAULT 'mean',
  lang TEXT NOT NULL DEFAULT 'en',
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  number TEXT NOT NULL DEFAULT '',
  kind TEXT NOT NULL DEFAULT 'K',
  code TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  contact_hours REAL NOT NULL DEFAULT 0,
  weight_pct REAL NOT NULL DEFAULT 0,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS assessments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  clo_id INTEGER NOT NULL REFERENCES clos(id) ON DELETE CASCADE,
  name TEXT NOT NULL DEFAULT '',
  max_mark REAL NOT NULL DEFAULT 0,
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS students (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  student_no TEXT NOT NULL DEFAULT '',
  name TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS grades (
  student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,
  mark REAL NOT NULL DEFAULT 0,
  PRIMARY KEY (student_id, assessment_id)
);

CREATE TABLE IF NOT EXISTS topics_not_covered (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  topic TEXT NOT NULL DEFAULT '',
  reason TEXT NOT NULL DEFAULT '',
  impact TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS improvement_plans (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  recommendation TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL DEFAULT '',
  support TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS signatures (
  course_id INTEGER PRIMARY KEY REFERENCES courses(id) ON DELETE CASCADE,
  instructor_signature TEXT NOT NULL DEFAULT '',
  coordinator_signature TEXT NOT NULL DEFAULT ''
);
